import { Geist, Geist_Mono } from "next/font/google";
import { Gulzar } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gulzar = Gulzar({
  weight: "400",
  variable: "--font-gulzar",
  subsets: ["arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  links: [
    {
      rel: "preload",
      href: "https://cdn.jsdelivr.net/npm/jameel-noori@1.1.2/fonts/jameel-noori-nastaleeq.woff2",
      as: "font",
      type: "font/woff2",
      crossOrigin: "anonymous",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="ur" dir="rtl" className={gulzar.variable}>
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/jameel-noori@1.1.2/jameel-noori.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-gulzar antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
